### ISSUE TITLE
RKE_CLOUD_CONFIG_CHECKSUM is appended instead of overwitten

### ISSUE THREAD

**Issue by walkafwalka** [rancher/terraform-provider-rke#120]
Every time I make a change to `rke_cluster` with `cloud_provider` configured, it appends `RKE_CLOUD_CONFIG_CHECKSUM` to the `extra_env` options.

```
...
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env:
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
    - RKE_CLOUD_CONFIG_CHECKSUM=d41d8cd98f00b204e9800998ecf8427e
...
cloud_provider:
  name: aws
```

```
resource "rke_cluster" "this" {
  cloud_provider {
    name = "aws"
  }

  nodes {
    address = aws_instance.this[0].private_dns
    user    = "rancher"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = tls_private_key.this.private_key_pem
  }

  nodes {
    address = aws_instance.this[1].private_dns
    user    = "rancher"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = tls_private_key.this.private_key_pem
  }

  nodes {
    address = aws_instance.this[2].private_dns
    user    = "rancher"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = tls_private_key.this.private_key_pem
  }

  services_etcd {
    backup_config {
      interval_hours = 6
      retention      = 90

      s3_backup_config {
        access_key  = aws_iam_access_key.etcd_snapshots.id
        secret_key  = aws_iam_access_key.etcd_snapshots.secret
        bucket_name = aws_s3_bucket.etcd_snapshots.id
        endpoint    = "s3.amazonaws.com"
      }
    }
  }
}
```
