### ISSUE TITLE
Can not import a cluster with terraform-provider-rke V1.4.3.

### ISSUE THREAD

**Issue by LefterisBanos** [rancher/terraform-provider-rke#432]
Terraform: v1.5.0
RKE Terraform Provider: v1.4.3
RKE Cluster: v1.26.9-rancher1-1
RKE: 1.4.7

When importing a cluster using latest 1.4.3 version of the provider getting following error : 
`Error:
│ ============= RKE outputs ==============
│ time="2023-11-23T15:27:29+02:00" level=info msg="Creating RKE cluster..."
│
│ kubernetes version v1.26.9-rancher1-1 requires enable_cri_dockerd to be set to true`

Although is set: `enable_cri_dockerd: true`

How to reproduce:
Use a `cluster.yaml` file and a `cluster.rkestate` file for a running cluster created from RKE CLI.
At the `cluster.yaml` set the `enable_cri_dockerd: true`.

Import cluster using `terraform-provider-rke`:

`terraform import rke_cluster.qa  cluster.yml:cluster.rkestate`.

Import will fail, even if `enable_cri_dockerd` is properly set to `true`

**Comment by jiaqiluo** [comment]
Waiting for RC

**Comment by jiaqiluo** [comment]
the fix can be validated at https://github.com/rancher/terraform-provider-rke/releases/tag/v1.4.5-rc1

**Comment by Josh-Diamond** [comment]
Ticket # 432 - Test Results - ✅ 
---

Reproduced with RKE `v1.4.7` and TFP-RKE `v1.4.3`:
1. Using RKE `v1.4.7` -- create a standalone RKE cluster using the following cluster.yml:
```yaml
ssh_key_path: <path_to_ssh_key_here>
enable_cri_dockerd: true
kubernetes_version: v1.26.6-rancher1-1

nodes:
  - address: <REDACTED>
    internal_address: <REDACTED>
    user: ubuntu
    role: [etcd, controlplane, worker]

  - address: <REDACTED>
    internal_address: <REDACTED>
    user: ubuntu
    role: [etcd, controlplane, worker]

  - address: <REDACTED>
    internal_address: <REDACTED>
    user: ubuntu
    role: [etcd, controlplane, worker]

```
2. Once cluster is up and active, create a `main.tf` file with the following configurations, and run `terraform init`:
```terraform
terraform {
  required_providers {
    rke = {
      source = "rancher/rke"
      version = "1.4.3"
    }
  }
}

provider "rke" {}

resource "rke_cluster" "rke_cluster" {}
```
3. Once terraform has been successfully initialized, import the standalone RKE cluster created in step 1, by running the following command:
```
terraform import rke_cluster.rke_cluster cluster.yml:cluster.rkestate
```
4. Reproduced - `kubernetes version v1.26.6-rancher1-1 requires enable_cri_dockerd to be set to true`

Screenshot:
<img width="724" alt="Screenshot 2024-03-26 at 10 27 25 AM" src="https://github.com/rancher/terraform-provider-rke/assets/46494969/9be84a05-2298-470f-a88f-ece0c8b66c79">

---

Verified with RKE `v1.4.7` and TFP-RKE `v1.4.5-rc1`:
1. Using RKE `v1.4.7` -- create a standalone RKE cluster using the following cluster.yml:
```yaml
ssh_key_path: <path_to_ssh_key_here>
enable_cri_dockerd: true
kubernetes_version: v1.26.6-rancher1-1

nodes:
  - address: <REDACTED>
    internal_address: <REDACTED>
    user: ubuntu
    role: [etcd, controlplane, worker]

  - address: <REDACTED>
    internal_address: <REDACTED>
    user: ubuntu
    role: [etcd, controlplane, worker]

  - address: <REDACTED>
    internal_address: <REDACTED>
    user: ubuntu
    role: [etcd, controlplane, worker]

```
2. Once cluster is up and active, create a `main.tf` file with the following configurations, and run `terraform init`:
```terraform
terraform {
  required_providers {
    rke = {
      source = "terraform.local/local/rke"
      version = "1.4.5-rc1"
    }
  }
}

provider "rke" {}

resource "rke_cluster" "rke_cluster" {}
```
3. Once terraform has been successfully initialized, import the standalone RKE cluster created in step 1, by running the following command:
```
terraform import rke_cluster.rke_cluster cluster.yml:cluster.rkestate
```
4. Verified - cluster successfully imports; as expected

Screenshot:
![image(1)](https://github.com/rancher/terraform-provider-rke/assets/46494969/76870f7d-915f-45b0-a2b6-21dd211c9077)
